### ISSUE TITLE
Upload the manual for the technology preview

### ISSUE THREAD

**Issue by sberlin** [neonious/neonone_examples#2]
Accessing the manual and API description of the technology preview under https://www.neonious.com/TPManual now redirects to the more general documentation. Please provide the pdf or markdown (maybe with a deprecation notice) formerly available at that location, if you agree the docs for lowjs could already be incompatible.

**Comment by neoniousTR** [comment]
Done, /TPManual now works again. Thank you for the hint..

BTW: I will look at your pull request in the next 2 days.
